create table if not exists users
(
    id text not null primary key,
    aud text,
    role text,
    email text not null unique,
    encrypted_password text,
    email_confirmed_at DATETIME,
    invited_at DATETIME,
    confirmation_token text,
    confirmation_sent_at DATETIME,
    recovery_token text,
    recovery_sent_at DATETIME,
    email_change_token_new text,
    email_change boolean,
    email_change_sent_at DATETIME,
    last_sign_in_at DATETIME,
    raw_app_meta_data text,
    raw_user_meta_data text,
    is_super_admin boolean,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    phone text,
    phone_confirmed_at DATETIME,
    phone_change boolean,
    phone_change_token text,
    phone_change_sent_at DATETIME,
    confirmed_at DATETIME,
    email_change_token_current text,
    email_change_confirm_status text,
    banned_until text,
    reauthentication_token text,
    reauthentication_sent_at DATETIME,
    is_sso_user boolean,
    deleted_at DATETIME,
    display_name text
);

