//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "crunchyroll_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub promo_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub promo_description: Option<String>,
    pub last_public: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub channel_id: Option<String>,
    pub new: Option<bool>,
    #[sea_orm(column_type = "Double", nullable)]
    pub average_rating: Option<f64>,
    pub total_ratings: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_image_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wide_image_url: Option<String>,
    pub audio_locales: Option<Vec<String>>,
    pub subtitle_locales: Option<Vec<String>>,
    pub content_descriptors: Option<Vec<String>>,
    pub maturity_ratings: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extended_maturity_level: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extended_maturity_rating: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rating_system: Option<String>,
    pub episode_count: Option<i32>,
    pub season_count: Option<i32>,
    pub launch_year: Option<i32>,
    pub is_dubbed: Option<bool>,
    pub is_subbed: Option<bool>,
    pub is_mature: Option<bool>,
    pub is_simulcast: Option<bool>,
    pub tenant_categories: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
