//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub id: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub icon: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    pub nesting_level: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub display_order: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,
    #[sea_orm(has_many)]
    pub channels: HasMany<super::channels::Entity>,
    #[sea_orm(has_many)]
    pub group_members: HasMany<super::group_members::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub groups: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub links: HasOne<super::links::Entity>,
    #[sea_orm(has_many)]
    pub share_links: HasMany<super::share_links::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
