//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub target_url: String,
    #[sea_orm(has_many)]
    pub groups: HasMany<super::groups::Entity>,
    #[sea_orm(has_many)]
    pub link_statistics: HasMany<super::link_statistics::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
