//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "link_statistics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub link_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub referer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "link_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub links: HasOne<super::links::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
