//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod channels;
pub mod crunchyroll_channels;
pub mod group_members;
pub mod groups;
pub mod link_statistics;
pub mod links;
pub mod sessions;
pub mod settings;
pub mod share_links;
pub mod subscription_plans;
pub mod subscription_plans_users;
pub mod survey;
pub mod users;
pub mod videos;
pub mod youtube_channels;
