//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "share_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub group_id: String,
    #[sea_orm(unique)]
    pub link_code: String,
    pub link_type: String,
    pub permission: Option<String>,
    pub created_at: Option<DateTime>,
    pub expires_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub groups: HasOne<super::groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
