//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subscription_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub max_channels: i32,
    pub max_groups: i32,
    pub can_create_subgroups: bool,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_monthly: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_yearly: Decimal,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::subscription_plans_users::Entity")]
    SubscriptionPlansUsers,
}

impl Related<super::subscription_plans_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionPlansUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
