//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subscription_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub max_channels: i32,
    pub max_groups: i32,
    pub can_create_subgroups: bool,
    pub can_share_groups: bool,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_monthly: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_yearly: Decimal,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub subscription_plans_users: HasMany<super::subscription_plans_users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
