//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "survey")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub survey_text: String,
}

impl ActiveModelBehavior for ActiveModel {}
