//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub aud: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub role: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub encrypted_password: Option<String>,
    pub email_confirmed_at: Option<DateTime>,
    pub invited_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub confirmation_token: Option<String>,
    pub confirmation_sent_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recovery_token: Option<String>,
    pub recovery_sent_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_token_new: Option<String>,
    pub email_change: Option<bool>,
    pub email_change_sent_at: Option<DateTime>,
    pub last_sign_in_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_app_meta_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_user_meta_data: Option<String>,
    pub is_super_admin: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    pub phone_confirmed_at: Option<DateTime>,
    pub phone_change: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone_change_token: Option<String>,
    pub phone_change_sent_at: Option<DateTime>,
    pub confirmed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_token_current: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_confirm_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub banned_until: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reauthentication_token: Option<String>,
    pub reauthentication_sent_at: Option<DateTime>,
    pub is_sso_user: Option<bool>,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(has_many = "super::group_members::Entity")]
    GroupMembers,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::subscription_plans_users::Entity")]
    SubscriptionPlansUsers,
    #[sea_orm(has_many = "super::youtube_channels::Entity")]
    YoutubeChannels,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::group_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMembers.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscription_plans_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionPlansUsers.def()
    }
}

impl Related<super::youtube_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::YoutubeChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
