//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub aud: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub role: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub encrypted_password: Option<String>,
    pub email_confirmed_at: Option<DateTime>,
    pub invited_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub confirmation_token: Option<String>,
    pub confirmation_sent_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recovery_token: Option<String>,
    pub recovery_sent_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_token_new: Option<String>,
    pub email_change: Option<bool>,
    pub email_change_sent_at: Option<DateTime>,
    pub last_sign_in_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_app_meta_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_user_meta_data: Option<String>,
    pub is_super_admin: Option<bool>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    pub phone_confirmed_at: Option<DateTime>,
    pub phone_change: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone_change_token: Option<String>,
    pub phone_change_sent_at: Option<DateTime>,
    pub confirmed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_token_current: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_change_confirm_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub banned_until: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reauthentication_token: Option<String>,
    pub reauthentication_sent_at: Option<DateTime>,
    pub is_sso_user: Option<bool>,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(has_many)]
    pub channels: HasMany<super::channels::Entity>,
    #[sea_orm(has_many)]
    pub group_members: HasMany<super::group_members::Entity>,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,
    #[sea_orm(has_many)]
    pub subscription_plans_users: HasMany<super::subscription_plans_users::Entity>,
    #[sea_orm(has_many)]
    pub youtube_channels: HasMany<super::youtube_channels::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
